services:
  homehub:
    container_name: homehub
    # image: ghcr.io/surajverma/homehub:latest
    build: .
    ports:
      - "5005:5005"
    volumes:
      - ./uploads:/app/uploads
      - ./media:/app/media
      - ./pdfs:/app/pdfs
      - ./data:/app/data
      - ./config.yml:/app/config.yml:ro
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-}
